spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    database: H2

  datasource:
    url: jdbc:h2:tcp://localhost/~/car
    username: root
    password: root
    driver-class-name: org.h2.Driver
